name: xsop_forum
description: XSOP Forum - Flarum client built with Flutter.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  shared_preferences: ^2.2.0
  # [修改备注：新增 html 解析插件，用于在详情页真实渲染 Flarum 的富文本帖子内容]
  flutter_widget_from_html: ^0.15.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  image_path: "assets/icon.png"
  ios: true             
  android: true         
  remove_alpha_ios: true

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  shared_preferences: ^2.2.0
  flutter_widget_from_html: ^0.15.1
  # 新增系统分享插件
  share_plus: ^10.1.0
