name: xsop_forum
description: XSOP Forum - Flarum client built with Flutter.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  # 合并到这里的图标生成依赖
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

# 保持在文件最下方的图标配置块：
flutter_launcher_icons:
  image_path: "assets/icon.png"
  ios: true             # 自动替换 iOS 图标
  android: true         # 自动替换 Android 图标
  remove_alpha_ios: true # 自动移除 iOS 图标的透明度（苹果强制要求图标不能包含透明通道）
